name: test

on:
  push:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Install shfmt
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - name: Lint
        run: npm run lint:sh

      - name: Install ShellCheck v0.11.0
        run: |
          curl -sSL "https://github.com/koalaman/shellcheck/releases/download/v0.11.0/shellcheck-v0.11.0.linux.x86_64.tar.xz" | tar -xJ
          sudo mv shellcheck-v0.11.0/shellcheck /usr/local/bin/shellcheck

      - name: Test
        run: npm run test:sh

  test-ps:
    name: test (powershell)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install PSScriptAnalyzer and Pester
        run: npm run install:ps

      - name: Lint
        run: npm run lint:ps

      - name: Test
        run: npm run test:ps
